site_name: MpApt
repo_name: MpApt

repo_url: https://github.com/Foso/MpApt
site_url: https://foso.github.io/MpApt
theme:
  name: 'material'
  palette:
    primary: 'deep-orange'
    accent: 'deep-purple'
  feature:
    tabs: true

nav:
  - 'Overview': index.md
  - 'Changelog': CHANGELOG.md