package de.jensklingenberg.mpapt.extension

import de.jensklingenberg.mpapt.AbstractProcessor
import org.jetbrains.kotlin.extensions.DeclarationAttributeAltererExtension

class MyDeclarationAttributeAltererExtension(generator: AbstractProcessor) : DeclarationAttributeAltererExtension